name: 'ci-bypass'
description: 'Bypass CI checks for GitHub Actions'
author: 'SigureMo'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  # Basic options
  github-token:
    description: 'GitHub token to interact with the GitHub API'
    required: false
  non-pull-request-event-strategy:
    description: 'Strategy to apply to non-pull-request events, can be always-skipped, never-skipped, or always-failed, default is always-failed'
    required: true
    default: 'always-failed'
  # Select the type of the rule
  type:
    description: 'Type of the rule, can be labeled, commented, approved, or composite'
    required: true
  # Common options for all types
  username:
    description: 'Username, can be a string or an array of strings separated by |'
    required: false
  user-team:
    description: 'User team, can be a string or an array of strings separated by |'
    required: false
  # For labeled rule
  label:
    description: 'Label name, can be a string or an array of strings separated by |'
    required: false
  # For commented rule
  comment-pattern:
    description: 'Comment regex pattern, can be a string or an array of strings separated by |'
    required: false
  # For commented rule
  composite-rule:
    description: 'Use any, all or not to combine multiple rules, need to be a JSON string'
    required: false

# Define your outputs here.
outputs:
  can-skip:
    description: 'Whether the action can be skipped'

runs:
  using: node20
  main: dist/index.js
