name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  github-token:
    description: 'GitHub token to interact with the GitHub API'
    required: false
  type:
    description: 'Type of the rule, can be labeled, commented, approved, or composite'
    required: true
  label:
    description: 'Label name, can be a string or an array of strings'
    required: false
  username:
    description: 'Username, can be a string or an array of strings'
    required: false
  user-team:
    description: 'User team, can be a string or an array of strings'
    required: false
  composite-rule:
    description: 'Use any, all or not to combine multiple rules, need to be a JSON string'
    required: false

# Define your outputs here.
outputs:
  can-skip:
    description: 'Whether the action can be skipped'

runs:
  using: node20
  main: dist/index.js
