name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  merge_group:

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: .node-version
          run-install: false
          cache: true

      - name: Install dependencies
        run: vp install --frozen-lockfile

      - name: Run checks
        id: vp-check
        run: vp check

      - name: Run tests
        id: vp-test
        run: vp test
