name: Example Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check-bypass:
    name: Check Bypass
    runs-on: ubuntu-latest
    outputs:
      can-skip: ${{ steps.check-bypass.outputs.can-skip }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: check-bypass
        name: Check Bypass
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-if: |
            {
              "any": [
                {
                  "type": "labeled",
                  "label": ["skip-ci: example", "skip-ci: all"],
                  "user-team": "ci-infra"
                }
              ]
            }

  test-action-not-bypass:
    needs: check-bypass
    if: ${{ needs.check-bypass.outputs.can-skip != 'true' }}
    name: Branch not bypass
    runs-on: ubuntu-latest

    steps:
      - name: Action Not Skipped
        id: not-bypass
        run: echo "::error ::Action not skipped, needs.check-bypass.outputs.can-skip is ${{ needs.check-bypass.outputs.can-skip }}"

  test-action-bypass:
    needs: check-bypass
    if: ${{ needs.check-bypass.outputs.can-skip == 'true' }}
    name: Branch bypass
    runs-on: ubuntu-latest

    steps:
      - name: Action Skipped
        id: bypass
        run: echo "::error ::Action skipped"
