name: Update Bundled JavaScript

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  merge_group:

permissions:
  contents: write

jobs:
  update-dist:
    name: Update dist/
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.UPDATE_DIST_TOKEN }}

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version: '24'
          cache: true

      - name: Install dependencies
        run: vp install --frozen-lockfile

      - name: Build dist/ Directory
        id: build
        run: vp pack

      # This will commit the updated `dist/` directory if it is different than
      # expected.
      - name: Commit Updated dist/
        id: commit
        env:
          GH_TOKEN: ${{ secrets.UPDATE_DIST_TOKEN }}
        run: |
          if [ ! -d dist/ ]; then
            echo "Expected dist/ directory does not exist.  See status below:"
            ls -la ./
            exit 1
          fi
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            git config user.name "ShigureNyako"
            git config user.email "shigure_nyako@outlook.com"
            git add dist/
            git commit -m "🍱 chore: update bundled JavaScript in dist/"
            git push
          else
            echo "No changes detected in dist/. No commit necessary."
          fi
